### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krahim**
Remote method suggested by @rubak

### CODE REVIEW

**Comment by krahim** [comment]
1. Will the user still have to ensure appropriate compilers and shared libraries are installed if remote is used?
2. I would like to keep this version identical to CRAN, except for the couple days where I integrate the changes.

**Comment by rubak** [comment]
Yes, you still need compilers installed etc. You just don't have to manually download and install the package. If you want to make it even easier for everyone you can join the free service <https://r-universe.dev>. It only takes a few minutes:

1. Go to <https://r-universe.dev> and click "setup" (goes to this link <https://github.com/apps/r-universe/installations/new)
2. Login with GitHub and add the `fftwtools` repo in the setup step.
3. Wait a few hours and go to <https://krahim.r-universe.dev> and check that `fftwtools` is listed.
4. Then you are done and users can install the development version with: `install.packages("fftwtools", repos = "https://krahim.r-universe.dev")`

You should then simply write this single command as the alternative install instruction and it has the benefit that you no longer need a compiler installed on Windows/Mac as it installs the binary version.

**Comment by krahim** [comment]
> Yes, you still need compilers installed etc. You just don't have to manually download and install the package. If you want to make it even easier for everyone you can join the free service https://r-universe.dev. It only takes a few minutes:
> 
> 1. Go to https://r-universe.dev and click "setup" (goes to this link <https://github.com/apps/r-universe/installations/new)
> 2. Login with GitHub and add the `fftwtools` repo in the setup step.
> 3. Wait a few hours and go to https://krahim.r-universe.dev and check that `fftwtools` is listed.
> 4. Then you are done and users can install the development version with: `install.packages("fftwtools", repos = "https://krahim.r-universe.dev")`
> 
> You should then simply write this single command as the alternative install instruction and it has the benefit that you no longer need a compiler installed on Windows/Mac as it installs the binary version.

I tried this today. I think there is a problem with fftw libs? 

https://krahim.r-universe.dev/

**Comment by krahim** [comment]
It says I cannot customize the build. 
https://r-universe.dev/help/

"Can I customize the package build process with custom options/tools/variables? — No. Think of R-universe more like your own mini-CRAN. The build environment is very similar to that of CRAN, if the package can build on CRAN, it will probably work on r-universe."

**Review by krahim — COMMENTED** [review]
After looking into it more, I feel it is not worth it.

**Comment by krahim** [comment]
Not doing this

**Comment by krahim** [comment]
Okay,
I want to be done with this. I uploaded the compile changes to CRAN. I realize it's soon but...
Providing it works, then I will ask R-universe about the problem--if I find someone to ask.
I really only want one version--no development version.

Thanks,
Karim

**Pull request closed without merging**
