### PR TITLE
Multidim FFT for general arrays in R.

### PR DESCRIPTION
**Pull request by rubak**
Hi, I've added a function `fftw_c2c_xd` for general dimensional arrays analogous to `fftw_c2c_2d`. I hope you find the suggestion useful. Of course you are free to rename it to anything you like.

### CODE REVIEW

**Comment by krahim** [comment]
Have you checked that this will pass  R CMD build --as-cran ?
Which version of R?

**Comment by rubak** [comment]
Given that it is 3,5 years since I made this pull request I don't remember the details :-)

Anyway, I just ran a `RMD check --as-cran` on the master branch that the pull request is coming from, and the only issue was that the version is 0.9.8 while the version on CRAN now is up to 0.9.9. I guess that will be fixed once you merge and update version number for next CRAN release. This was on R 4.0.2.

**Comment by krahim** [comment]
Thanks for your patience Rubak and quick reply.
I don't check this often. Seems I only pay attention when Brian Ripley threatens to archive a package...

I appreciate the contribution. 
I merged the pull, and it seems fine. I will submit this to CRAN in a bit. 
I just pushed an update, so I'll wait a week or so.

Please feel free to msg me.
Kind Regards!
Karim

**Comment by rubak** [comment]
No worries. Sounds good with an update some weeks from now (I think CRAN prefers something like 6-8 weeks if it isn't an urgent bugfix).
Maybe you should consider adding an updated configure script etc. as described in the open issue. Maybe you can ask the original poster that opened the issue to make his fixes into a pull request.
I will be happy to test this out before you submit to CRAN. I could make a pull request setting up GitHub Actions so you get automatic tests of the package with every commit and pull request on GitHub if that would be of interest?

**Comment by krahim** [comment]
Thanks Ege! 
I've asked for a pull request.

Karim

**Comment by krahim** [comment]
I appreciate the help Ege!

**Pull request merged**
