### PR TITLE
Configure compiler

### PR DESCRIPTION
**Pull request by dipterix**
Hi @krahim ,

Reference to #7 

Sorry for the late reply. Here are changes I made this January. Please **double check** before merging. So if I remember it correctly, your package was not using `configure` file, instead you hard-coded flags in `Makevars`. The issue was if user has different flags (like multiple fftw3 libraries in system and conda), the compiler won't be able to use the correct ones.

I copied some files from `fftw` package into your configure.ac. To make autoconf file work, you probably need to install [autoconf](https://www.gnu.org/software/autoconf/) on linux, or macosx, or docker. To automatically generate `configure` file, see [this](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#autoconf-Invocation).

### CODE REVIEW

**Comment by rubak** [comment]
I think this sounds like a good solution to find fftw on more systems. @krahim I suggest that you merge my pull request setting up GitHub Actions first, so you can see this suggested new workflow also passes with that setup. It would be nice to add more OS options to GitHub Actions, but I didn't have time to figure out how to properly install fftw on OSX and Windows, so it only tests on Ubuntu at the moment.

**Comment by dipterix** [comment]
@rubak On OSX, one can easily install via 
```
brew install fftw
```

On windows, I think R tools actually contains `fftw3`. See [here](https://github.com/r-windows/docs/blob/fb05dc543a0c94404c5826fcf1da8bc4cb57e12b/rtools40.md#example-installing-a-library-with-pacman)

**Comment by krahim** [comment]
Hi Dipterix,

I incorporated  the merge and I appreciate it. This is far from my main gig.

Anyways, I cannot pass the as-cran checks now. I suspect that an update occurred to R.

I'm wondering if you have any suggestions. 


I get the following:
R CMD check --as-cran fftwtools_0.9-10.tar.gz 

1.* checking whether package ‘fftwtools’ can be installed ... WARNING
Found the following significant warnings:
  'config' variable 'CPP' is deprecated
See ‘/home/karim/PWLisp/fftwtools.Rcheck/00install.out’ for details.

In the .out file I have the following:
* installing *source* package ‘fftwtools’ ...
** using staged installation
'config' variable 'CPP' is deprecated
checking for gcc... gcc -std=gnu99


2. Package has both ‘src/Makevars.in’ and ‘src/Makevars’.
Installation with --no-configure' is unlikely to work.  If you intended
‘src/Makevars’ to be used on Windows, rename it to ‘src/Makevars.win’
otherwise remove it.  If ‘configure’ created ‘src/Makevars’, you need a
‘cleanup’ script.

I cannot find a Makevars file. I do have a Makevars.win file.
I would appreciate any help.
R version 4.0.4 (2021-02-15) -- "Lost Library Book"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by krahim** [comment]
> I think this sounds like a good solution to find fftw on more systems. @krahim I suggest that you merge my pull request setting up GitHub Actions first, so you can see this suggested new workflow also passes with that setup. It would be nice to add more OS options to GitHub Actions, but I didn't have time to figure out how to properly install fftw on OSX and Windows, so it only tests on Ubuntu at the moment.

Doesn't CRAN build the MacOS and Windows binaries?

**Comment by krahim** [comment]
I backed it out to upload the update to cran. It did not pass --as-cran.

**Comment by dipterix** [comment]
I'll take a look

**Comment by krahim** [comment]
Another user just uploaded a that should incorporate it. 
I haven't tired it yet. I made a push to CRAN on the weekend when I tried to incorporate this.

What is the purpose of this change again?

**Comment by dipterix** [comment]
@krahim The purpose of this PR was to allow users to specify non-standard fftw3 path on macos or linux.

The reason why R check failed was because 

1. `CPP` flag was removed as of R 4.0
2. Since you are already using `autoconf`, there shouldn't be `arc/Makevar` anymore. Instead, you only need to write `src/Makevar.in` and use autoconf to generate `configure` file.

I've fixed these in my latest update here. Please feel free to make a pull request.
https://github.com/dipterix/fftwtools

Here's the check results on macOS and Ubuntu (using `--as-cran`)
https://github.com/dipterix/fftwtools/actions/runs/597868757

Since Eddel's version already works. It's safe to merge his PR, but you are more than welcome to take anything you feel useful from mine.

**Comment by krahim** [comment]
Much appreciated @dipterix!
I have a version that should work now.

Karim

**Pull request merged**
