### PR TITLE
Rewrite a simple configure.ac using pkg-config

### PR DESCRIPTION
**Pull request by eddelbuettel**
This adds a new and working configure.ac and configure updating a src/Makevars. It adds the created configure script, adds a cleanup script (also needed to remove generated src/Makevars) and updates src/Makevars to src/Makevars.in to work with configure.

I can walk through any questions you may have.

### CODE REVIEW

**Comment by krahim** [comment]
> This adds a new and working configure.ac and configure updating a src/Makevars. It adds the created configure script, adds a cleanup script (also needed to remove generated src/Makevars) and updates src/Makevars to src/Makevars.in to work with configure.
> 
> I can walk through any questions you may have.

Thanks,

I just pushed an update to CRAN last night. 
Did you run R CMD check --as-cran

If so can you confirm that it did pass *without* any warnings or notes?

**Comment by eddelbuettel** [comment]
Yes of course it does.  

I am this one commit ahead of you:

```
edd@rob:~/git/fftwtools(master)$ git ls | head -2
* ce19905 - (HEAD -> master, origin/master, origin/HEAD) rewrite simple configure.ac (43 minutes ago) <Dirk Eddelbuettel>
* 3c31653 - update instructions (17 hours ago) <krahim>
edd@rob:~/git/fftwtools(master)$ 
```

Build:

```sh
edd@rob:~/git/fftwtools(master)$ R CMD build .                                                           
* checking for file ‘./DESCRIPTION’ ... OK                                                               
* preparing ‘fftwtools’:                                                                                 
* checking DESCRIPTION meta-information ... OK
* cleaning src                                 
* running ‘cleanup’                    
* installing the package to build vignettes
* creating vignettes ... OK                   
* cleaning src            
* running ‘cleanup’          
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘fftwtools_0.9-10.tar.gz’               
                                                    
edd@rob:~/git/fftwtools(master)$
```

Check

```sh
edd@rob:~/git/fftwtools(master)$ R CMD check --as-cran fftwtools_0.9-10.tar.gz 
* using log directory ‘/home/edd/git/fftwtools/fftwtools.Rcheck’
* using R version 4.0.4 (2021-02-15)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘fftwtools/DESCRIPTION’ ... OK
* this is package ‘fftwtools’ version ‘0.9-10’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘fftwtools’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: OK

edd@rob:~/git/fftwtools(master)$ 
```

If you look at the changes I made _none affect any actual running code_ in either `src/` or `R/` but they "merely" replace the hardcoded values for the required `fftw3` library with setting derived at build by querying `pkg-config`.

**Comment by eddelbuettel** [comment]
This is in response to your email to r-package-devel as well the numerous "questions" and "notes" you have in the repo.  If you want to ask short precise questions about `configure`, `autoconf` and all that I can help.  A lot is actually also in _Writing R Extensions_, but as usual a little dense.  There are _many_ example packages at CRAN you could study too.

Again, if you have questions I am happy to help.

**Comment by eddelbuettel** [comment]
And for good measure, R-devel (which I have locally here too).   It notices the non-incemented version which is actually correct:

```sh
edd@rob:~/git/fftwtools(master)$ rdcc.sh fftwtools_0.9-10.tar.gz   ## simple shell wrapper setting PATH etc for r-devel
* using log directory ‘/tmp/fftwtools.Rcheck’
* using R Under development (unstable) (2021-02-15 r80007)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8                     
* using option ‘--as-cran’                         
* checking for file ‘fftwtools/DESCRIPTION’ ... OK
* this is package ‘fftwtools’ version ‘0.9-10’
* checking CRAN incoming feasibility ... WARNING                                                         
Maintainer: ‘Karim Rahim <karim.rahim@queensu.ca>’
                                                                                                         
Insufficient package version (submitted: 0.9.10, existing: 0.9.10)
                                                    
Days since last update: 0                        
* checking package namespace information ... OK                                                          
* checking package dependencies ... NOTE        
Package suggested but not available for checking: ‘fftw’ 
* checking if this is a source package ... OK      
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK                                                       
* checking for portable file names ... OK        
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘fftwtools’ can be installed ... OK
* checking installed package size ... OK         
* checking package directory ... OK              
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK                                                                      
* checking DESCRIPTION meta-information ... OK      
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 WARNING, 1 NOTE
See
  ‘/tmp/fftwtools.Rcheck/00check.log’
for details.


edd@rob:~/git/fftwtools(master)$ 
```

**Comment by krahim** [comment]
I appreciate this. 
A change like this was suggested by another user, but I could not resolve the Warnings and Notes, and I did not incorporate it when I made a push to CRAN over the weekend.

What is the purpose of this change again?

**Comment by eddelbuettel** [comment]
Not to put too fine a touch on it but you have a dozen question notes (and I appreciate the transparency) cluttered over half a dozen files in your repo -- it looks like you want to learn more about how this works.  You have a package structure, that while not in conflict with `R CMD check` (or else you would have done it) is in conflict with itself (a source `configure.ac` but no generated `configure`, a `configure.ac` but no `src/Makevars.in` to alter it, a suboptimal `src/Makevars` with hardwired fixed values, ...).

I told you above in the first line of the first paragraph what this is about: 

> This adds a new and working configure.ac and configure updating a src/Makevars. 

I can help you work through this and get a better understanding.  It will make your package better.  You are _of course_ entirely free to ignore, if so it would be better to say so sooner rather than later.  Waiting two days, and not following up to my email on r-package-devel wastes everybody's time.  I have 60+ packages on CRAN and solved these questions a few times over, and I have helped others to spread the knowledge a little.  All I am doing is offering you some help.

**Comment by eddelbuettel** [comment]
In its barest essence we do two things:
- because you have a HARD depends on R package fftw, it is very likely that libfftw3 is present
- we check for pkg-config and abort if it isn't found; an uncommon situation
- we then use pkg-config to learn which, if any, values we have to pass to the compiler to find fftw3 headers
- and we use pkg-config to learn which, if any, values we have to pass to the linker to find and use the fftw3 library
and with that your package package will build from source in more situations than currently where libfftw3 is required to be in a system location. How to use `pkg-config` is explained for example [here in the Writing R Extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Configure-and-cleanup) and I use it myself in a few other packages.

**Comment by krahim** [comment]
Much appreciated!

Why do we have to specify the fftwtools version in the config file? Is there a way to just do this in the Description file?


AC_INIT([fftwtools], [0.9-10])

**Comment by eddelbuettel** [comment]
That is a good question.  I do it in most of mine because it seems like common (and good) practice. You can see the effect after `autoconf; ./configure --help | head`.   With this line it identifies itself, without it doesn't.

But the line has no "functional" effect. It will work without it.  But if you look at, say, R's own `configure.ac` or many others you see it is common.

`autoconf` and `configure` are very quirky and very old and, once you get the hang, very good and robust.  There used to be one or two good tutorials out there but some have vanished.  You can google for "autoconf tutorials" and also (as it is part of `autotools`) "autotools tutorial" but it gets quirky quickly.  Working examples are great, and CRAN has a few ...

**Review by krahim — APPROVED** [review]

**Comment by krahim** [comment]
Hi,

I tried R Universe based on @rubak suggestion. Unfortunately it did not build.
I tried it after updating the build --without the hard coded fftw libs.

I'm wondering if you have any suggestions?

Thanks!
https://krahim.r-universe.dev/

**Comment by eddelbuettel** [comment]
It may be missing the system dependency (and/or the dependency on `pkg-config` which may arguably be missing from your `DESCRIPTION` file).   

You cannot enforce system dependencies as a CRAN package, only suggest it.  I suggest you contact the universe maintainer.

**Comment by krahim** [comment]
Okay,
I want to be done with this. I uploaded the compile changes to CRAN. I realize it's soon but...
Providing it works, then I will ask R-universe about the problem--if I find someone to ask.
I really only want one version--no development version.

Thanks,
Karim

**Comment by eddelbuettel** [comment]
There was no requested CRAN change so no hurry there as far as I can tell.

(Very personally speaking) I have a number of design issue with R Universe so I will not comment further on that -- but I _would be happy_ to send you another (mini) PR with a working GitHub Actions setup which will give working Continuous Integration at GitHub for free.  I wrote / spoke about [my approach here](http://dirk.eddelbuettel.com/blog/2021/01/07/#032_portable_ci_with_r-ci), there of course other but that is what works well for me across several dozen repos and CRAN packages.

**Comment by rubak** [comment]
@krahim I see how you don't really have a great need for an easy to install development version since you mainly implement requested features in a short development sprint and then submit to CRAN right away. The value of R Universe is really when you need to deploy a development version of a package that is somewhat difficult to install from source. My experience with R Universe is very limited, but it worked out of the box with what I tested. Since you don't need it, there is no need to spend more time on it, but I guess the maintainer would appreciate the bug report to help make the tool better.

However, I highly recommend you accept the generous offer from @eddelbuettel to get full Continuous Integration using GitHub Actions. This is really helpful for you to see whether pull requests are passing R CMD check without having to do anything on your end. With the current GitHub Actions setup you can e.g. see that your latest version doesn't pass the checker:
<https://github.com/krahim/fftwtools/runs/1948426481?check_suite_focus=true#step:8:50>

My half baked effort only gives you a check on Linux, but my guess is that @eddelbuettel can make this check more complete across platforms and R versions so you get automated checks on Mac and Windows as well.

**Comment by eddelbuettel** [comment]
(No, I'd also only do Linux which is good enough for me in almost all cases. In "simple cases" adding macOS is fine; but when external libraries are needed I _clearly_ stick to Linux only where that is usually easy for me as I know my way around `apt` and friends.)

**Comment by rubak** [comment]
OK. Then @eddelbuettel's version would probably just be an updated version of [what I did here](https://github.com/krahim/fftwtools/actions/runs/587649157/workflow). Anyway, if @krahim doesn't like GitHub Actions a new take on it doesn't help much.

**Comment by eddelbuettel** [comment]
Yes indeed!  Did you see what I at the updated website for it: [r-ci](https://eddelbuettel.github.io/r-ci) along with for example this [January 7 blog post](http://dirk.eddelbuettel.com/blog/2021/01/07#032_portable_ci_with_r-ci) with the associated video?  It's all a little cleaner/simpler now and can use [bspm](http://cloud.r-project.org/package=bspm) which can make a few things simpler.

**Comment by rubak** [comment]
Yes, the r-ci website is cool and nicely illustrates how simple this is to set up.

If you need a new topic for your blog I'm waiting for the authoritative guide on how to setup reverse dependency checks for a package with many-ish (~100) reverse dependencies ;-) With Rcpp likely hitting 1000s of reverse dependencies you must have the tools set up. Is it a docker with `apt install` a gazillion system libraries or how do you setup a machine to be able to run the checks? I have seen your post on `prrd`, but as I understand, that only covers the actual running of checks and not setting up the system. Anyway, I do realize that you have plenty of things on your plate, and I don't expect you to run a "blog post by mail order" service, so please only see this as a note that at least one person would be interested if you found the topic well suited for a blog post at some point.

**Comment by eddelbuettel** [comment]
There is simply no short cut.  I just ran `prrd` again for Rcpp and RcppArmadillo this weekend mostly to .... find the dozen or so new system dependencies I needed to install for newly added CRAN packages whose initial checks failed for lacks.   Maybe we should have that discussion over at `prrd`.  

(And not to show off but Rcpp is north of 2200, RcppArmadillo is north of 800 and so on ...)

**Pull request merged**
