### PR TITLE
Adds fftw3d and related functions for 3D FFT

### PR DESCRIPTION
**Pull request by jmarshallnz**
This just implements the 3D versions of FFT in the same way the 2D ones are implemented. Would be nice to have this in the package by default.

(I guess also the full multivariate one I suppose?)

Tested and confirmed identical to stats::fft on 3D arrays.

### CODE REVIEW

**Comment by krahim** [comment]
Thanks.
Can you confirm that these will work if with R CMD check --as-cran  

Which version of R?

**Comment by jmarshallnz** [comment]
Considering this was submitted over 3 years ago, my guess is I can't guarantee any of this :)

However, if you like I can probably take some time to rebase this branch up - particularly if you are aiming for release soon?

**Comment by krahim** [comment]
Hi Jonathan,

I appreciate your request and apologize. 

Yeah it seems I only pay attention when Brian Ripley threatens to archive one of my R packages. 

I just pushed an update to CRAN last weekend, and after that I accepted @rubak pull request for multi dim arrays. 
I think the multi-dim covers your request? I will likely do another push in 6 to 8 week.

If you feel multi-dim doesn't cover your request then I'm happy to add 3D providing. 
What do you think?

Karim

**Comment by jmarshallnz** [comment]
Hah - we all need a bit of motivation, eh? :)

Not sure if multi-dim covers it. It may well do (just not sure if the data organisation is similar to what we were originally wanting it for).

Will check it out over the next week or so - have in the meantime checked and the rebase here passes --as-cran OK.

**Comment by jmarshallnz** [comment]
Ok, I've checked what we were using it for, and it seems it'd be more convenient to have these implemented directly if at all possible, as it simplifies the calling process for real matrices, which I'm guessing is what lots of folk will be using.

An alternate is extending the multidim work to include the real->complex case, which fftw seems to support by my reading, but I figure as fftw itself has specific 3d versions, keeping the API at the R level similar has some advantages!

Thus, I'd favour including this as-is I think.

**Comment by krahim** [comment]
Thanks!

**Pull request merged**
